import type { ReviewHistoryRecord } from "@/types/review-history";

export const REVIEW_HISTORY_MOCK_DATA: ReviewHistoryRecord[] = [
    {
        id: "rh-001",
        resourceId: "res-101",
        resourceTitle: "Suzhou Embroidery Traditions",
        reviewerId: "user-r-001",
        reviewerName: "Demo Reviewer",
        reviewerEmail: "reviewer@heritage.demo",
        reviewerEmployeeId: "EMP-R-1001",
        decision: "APPROVED",
        comments: "Well-documented resource with sufficient supporting context.",
        reviewedAt: "2026-04-05T10:30:00Z",
    },
    {
        id: "rh-002",
        resourceId: "res-102",
        resourceTitle: "Ancient Canal Folk Songs",
        reviewerId: "user-r-001",
        reviewerName: "Demo Reviewer",
        reviewerEmail: "reviewer@heritage.demo",
        reviewerEmployeeId: "EMP-R-1001",
        decision: "REJECTED",
        comments:
            "The description is too brief and does not provide enough cultural context.",
        reviewedAt: "2026-04-05T14:10:00Z",
    },
    {
        id: "rh-003",
        resourceId: "res-103",
        resourceTitle: "Stone Bridge Restoration Archive",
        reviewerId: "user-a-001",
        reviewerName: "Demo Admin",
        reviewerEmail: "admin@heritage.demo",
        reviewerEmployeeId: "EMP-A-2001",
        decision: "APPROVED",
        comments: "Metadata is complete and image evidence is appropriate.",
        reviewedAt: "2026-04-06T09:20:00Z",
    },
    {
        id: "rh-004",
        resourceId: "res-104",
        reviewerId: "user-a-001",
        reviewerName: "Demo Admin",
        reviewerEmail: "admin@heritage.demo",
        reviewerEmployeeId: "EMP-A-2001",
        resourceTitle: "Temple Festival Photo Collection",
        decision: "REJECTED",
        comments:
            "Copyright declaration is unclear. Please clarify ownership before resubmitting.",
        reviewedAt: "2026-04-06T16:45:00Z",
    },
    {
        id: "rh-005",
        resourceId: "res-105",
        resourceTitle: "Local Pottery Workshop Record",
        reviewerId: "user-r-002",
        reviewerName: "Lois Zhu",
        reviewerEmail: "lois.zhu@heritage.demo",
        reviewerEmployeeId: "EMP-R-1002",
        decision: "APPROVED",
        comments: "Good supporting links and category selection.",
        reviewedAt: "2026-04-07T08:15:00Z",
    },
    {
        id: "rh-006",
        resourceId: "res-106",
        resourceTitle: "Community Oral History Notes",
        reviewerId: "user-r-002",
        reviewerName: "Lois Zhu",
        reviewerEmail: "lois.zhu@heritage.demo",
        reviewerEmployeeId: "EMP-R-1002",
        decision: "REJECTED",
        comments:
            "More evidence is needed to support authenticity and relevance.",
        reviewedAt: "2026-04-07T11:40:00Z",
    },
];